### ISSUE TITLE
[Bug]: nexus 포트 9090 을 8081 로 수정 요청

### ISSUE THREAD

**Issue by LeeBaekHaeng** [eGovFramework/egovframe-development#113]
### 오류 내용 Error Description

오류를 발견했어요. I found an error.

nexus 포트 9090 을 8081 로 수정 요청

서버용 개발환경(Development Tool - Unix,Linux,Win64bit) 4.2.0 게시판 내용 수정 요청

https://www.egovframe.go.kr/home/sub.do?menuNo=94

서버용 개발환경(Development Tool - Unix,Linux,Win64bit) 4.2.0

```
* http://localhost:9090/nexus
* 사용포트 변경시(eGovCI-4.2.0/bin/apache-tomcat-nexus/conf/server.xml) 파일수정
```
를
```
* http://localhost:8081/nexus
* 사용포트 변경시(eGovCI-4.2.0/bin/nexus-2.15.1-02-bundle/nexus-2.15.1-02/conf/nexus.properties) 파일수정
```
로 수정

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

**Comment by overpassion** [comment]
감사합니다.
덕분에 해당 내용으로 보완 하였습니다.
