### ISSUE TITLE
[Bug]: eGovCI-4.2.0.tar.xz 에 jdk 추가 요청

### ISSUE THREAD

**Issue by LeeBaekHaeng** [eGovFramework/egovframe-development#114]
### 오류 내용 Error Description

오류를 발견했어요. I found an error.

eGovCI-4.2.0.tar.xz 에 jdk 추가 요청

윈도우에는 jdk 가 있어서 리눅스에도 추가할 수 있을까요?

**리눅스
eGovCI-4.2.0/bin/jdk8u242-b08
eGovCI-4.2.0/bin/jdk-11.0.5
eGovCI-4.2.0/bin/jdk-17.0.10+7**

윈도우
eGovCI-4.2.0_64bit/bin/jdk8u242-b08
eGovCI-4.2.0_64bit/bin/jdk-11.0.5
eGovCI-4.2.0_64bit/bin/jdk-17.0.10+7

https://www.egovframe.go.kr/home/sub.do?menuNo=94

서버용 개발환경(Development Tool - Unix,Linux,Win64bit) 4.2.0

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

**Comment by overpassion** [comment]
Linux의 경우 apt, yum, dnf등의 패키지 관리자로 쉽게 설치가 되기 때문에 포함되어 있지는 않습니다.
검토하도록 하겠습니다. 감사합니다.
