### ISSUE TITLE
[Bug]: Nexus - JDK 1.8 필요 JVM 실행 파일 설정 내용 추가

### ISSUE THREAD

**Issue by LeeBaekHaeng** [eGovFramework/egovframe-development#115]
### 오류 내용 Error Description

오류를 발견했어요. I found an error.

Nexus - JDK 1.8 필요 JVM 실행 파일 설정 내용 추가

```
==================================================
* Nexus - JDK 1.8 필요,Jenkins - JDK 11 이상 svn은 별도로 설치 필요
JAVA_HOME 설정이 필요한 경우 : setEnv.sh(환경설정)파일에서 export JAVA_HOME을 강제로 지정할 것
TOMCAT 메모리 설정이 필요한 경우 : setEnv.sh(환경설정)파일에서 CI_OPTS 설정을 변경
실행파일 start-xxx.sh
==================================================
```
를
```
==================================================
* Nexus - JDK 1.8 필요,Jenkins - JDK 11 이상 svn은 별도로 설치 필요
Nexus - JDK 1.8 필요: eGovCI-4.2.0/bin/nexus-2.15.1-02-bundle/nexus-2.15.1-02/bin/jsw/conf/wrapper.conf
wrapper.java.command=/eGovCI-4.2.0/bin/jdk8u242-b08/bin/java
JAVA_HOME 설정이 필요한 경우 : setEnv.sh(환경설정)파일에서 export JAVA_HOME을 강제로 지정할 것
TOMCAT 메모리 설정이 필요한 경우 : setEnv.sh(환경설정)파일에서 CI_OPTS 설정을 변경
실행파일 start-xxx.sh
==================================================
```
로 수정

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

**Comment by overpassion** [comment]
수고하셨습니다.
즉시 반영 하였습니다.
감사합니다~
