### ISSUE TITLE
[기능요구(Feature)]: Spring AI 를 이용한 기능이 추가 되면 좋겠습니다

### ISSUE THREAD

**Issue by youngick** [eGovFramework/egovframe-development#119]
### 연락처 Contact

youngick@paran.com

### 추가 요청 기능명 Feature Name

Spring AI 를 이용한 챗봇/문서 요약 등의 기능을 개발할 수 있는 기능이 추가되면 좋겠습니다.

### 기능 상세 설명 Feature Description

최근 생성형 AI를 이용한 챗봇, 번역, 문서 요약, 검색 등을 도입하는 요구사항이 많아져서 
Spring AI 를 이용하여 기능을 개발할 수 있으면 좋겠습니다.

### 솔루션 관련 URL Solution-related URLs

https://spring.io/projects/spring-ai

**Comment by overpassion** [comment]
좋은의견 감사합니다.
