### ISSUE TITLE
FindBugs 사용법 문서 컨트리뷰션

### ISSUE THREAD

**Issue by WooYoungsik** [eGovFramework/egovframe-development#21]
**1. FindBugs란?**
FindBugs는 Maryland 대학 연구 프로젝트 결과물로 자바 소스의 컴파일 된 클래스 파일을 검사하는 오픈 소스 정적 분석 도구다. 정적 분석 도구이므로 프로그램을 실행하지 않고도 프로그램 소스(정확히는 자바 바이트 코드)를 검사할 수 있다. 
정적 분석을 통해 찾아내고자 하는 것은 프로그램 내에 존재하는 잠재적인 결함이다.
결함을 찾아 내는 과정은 FindBugs내에 있는 결함 패턴과 클래스 파일을 비교하여 잠재적인 자바 코드 결함을 찾아낸다. 
FindBugs가 찾아낸 잠재적인 결함은 실제 결함일 수도 있고 아닐 수도 있다. 따라서 찾아낸 결함들은 코드 리뷰를 통해 실제 결함인지 아닌지 판별하는 과정을 거쳐야 하다. 프로젝트에서는 해당 모듈 개발자가 이 업무를 수행하게 된다.
그리고 FindBugs가 찾아낸 결함은 코딩 스타일이나 포맷 등과 관련이 없다. 잠재적인 결함, 성능 문제 등을 찾아낸다.

**2. FindBugs 실행하기**
FindBugs는 GUI, Command Line 형태, Ant Task, 이클립스 플러그인 형태로 실행할 수 있다. FindBugs에서 공식적으로 지원하지 않지만 Maven플러그 인을 이용하여 실행할 수도 있다. GUI 형태로 실행하는 것보다 이클립스 플러그인을 설치하여 이클립스 안에서 사용하는 것이 가장 사용하기 편하다.
FindBugs 이클립스 플러그인은 아래 공식 업데이트 사이트를 통해 설치하면 된다.
http://findbugs.cs.umd.edu/eclipse/
설치 후 실행은 패키지 익스플로러에서 검사하고 싶은 프로젝트를 선택하고 오른쪽 마우스 버튼을 누른 뒤 나타내는 메뉴에서 FindBugs를 선택하면 된다.
FindBugs가 자동으로 실행되게 설정하면 이클립스내에서 클래스 파일이 수정될 때 마다 FindBugs가 자동으로 실행된다.
아래 화면과 같이 이클립스내 자바 프로젝트 등록정보 -> 프로젝트 프로퍼티 설정 윈도우 -> Findbugs -> Run automatically를 체크하면 된다.
![image](https://user-images.githubusercontent.com/70587865/127353372-80381c72-ca7e-4704-bc7f-18deb7625293.png)
[그림1]FindBugs 자동 실행 설정

프로젝트를 진행할 경우 개발자들 자율에 맡기는 것보다 CI(Continuous Integration)를 구성하여 자동화된 빌드 프로세스(Daily Build 등)내에서 FindBugs를 실행하여 강제로 정적 코드 검사를 수행하는 것이 바람직하다. 이 경우 소나큐브(FindBugs 플러그인)와 젠킨스를 사용하여 CI를 구성하는 것이 좋다. 
CI 구성을 하지 않는 경우에도 FindBugs 플러그인을 포함한 상태에서 소나큐브를 실행하는 것이 좋다. 이 경우 소나큐브의 웹포탈 대시보드 화면을 통해 FindBugs가 발견한 결함, 결함의 의미, 해당 결함이 발생한 소스들을 살펴볼 수 있다.

소나큐브에서 사용하는 소나큐브-FindBugs 플러그인은 FindBugs, FindSecurityBugs, fp-contrib 등을 모두 포함하고 있어서 설치/사용이 간편하다.( FindSecurityBugs, fp-contrib에 대한 내용은 아래에 설명되어 있다.)

어떤 형태로 FindBugs를 실행하던지 FindBugs의 사용법은 어렵지 않다. 
중요한 부분은 사용법이 아니라 FindBugs가 발견하여 리포팅한 잠재적 결함이 무엇인지 결함의 내용과 의미를 정확히 이해하는 것이다. 해당 결함의 내용이 무엇인지 이해하고 자신이 개발한 코드가 해당 결함을 가지고 있는지 판단을 해야 한다. 오탐의 경우도 있으므로 실제 결함인지 여부의 최종 결정은 사람이 해야 한다.

**3. Findbugs로 탐지 가능한 결함 유형**
2015년 3월 이후 오랫동안 업그레이드가 되지 않고 있지만 FindBugs 최신 버전인 3.0.1에서 탐지할 수 있는 결함 패턴은 400개가 넘는다. 이 결함 패턴들은 아래와 같은 9 가지 이상의 카테고리로 분류된다.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/abc/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/abc/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/abc/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=KO style='tab-interval:40.0pt'>

탐지   유형 | 탐지   내용
-- | --
Bad Practice | 발생된   예외 무시, null 처리 실수 등 개발자의 나쁜 습관을 탐지
Correctness | 무한재귀호출, write된 적이 없는 field 참조 등 문제의 소지가 있는 코드를 탐지
Dodgy code | 사용되지   않는 로컬 변수, 형 변환 체크 오류 등 부정확하거나 오류를 발생시킬 수 있는 코드를 탐지
Experimental | 메서드에서   생성된 stream이나 리소스가 해제되지 못한 코드를 탐지
Internationalization | Default 인코딩을 지정하지 않은 경우   등 지역특성을 고려하지 않은 코드 탐지
Malicious code vulnerability | 보안   코드에 취약한 가변적인 배열이나 컬렉션, Hashtable 탐지
Multithreaded correctness | 멀티   쓰레드에 안전하지 않은 객체 사용 등을 탐지
Performance | 미사용   필드, 비효율적 객체생성 등 성능에 영향을 주는 코드를 탐지
Security | CSS, DB 패스워드 누락 등 보안에 취약한   코드를 탐지

</body>

</html>

그리고 보안과 관련하여 추가로 121개의 보안 관련 결함 패턴을 탐지할 수 있는 FindSecurityBugs가 있다. FindSecurityBugs는 FindBugs 플러그인으로 http://find-sec-bugs.github.io/ 사이트에서 다운로드하여 FindBugs에 설치하면 된다. FindSecurityBugs는 FindBugs와 달리 최근까지 업데이트가 이루어지고 있다.

**4. FindBugs 추가 결함 탐지기**
http://fb-contrib.sourceforge.net/ 사이트에서 FindBugs의 추가 결함 탐지기를 다운로드 할 수 있다. 이클립스에서 FindBugs 플러그인을 사용하고 있다면 위 사이트에서 다운로드 받은 추가 결함 탐지기 플러그인 파일(예, fb-contrib-7.0.3.sb.jar)을 하기 폴더에 복사한 뒤 이클립스를 재시작하면 된다. fp-contrib를 사용하면 좀 더 많은 결함을 탐지할 수 있다.

\이클립스 설치 폴더\plugins\edu.umd.cs.findbugs.plugin.eclipse_3.0.1.xxx\plugin

**5. 잠재적 자바 코드 결함 탐지**
이후부터는FindBugs가 찾아내는 잠재적 자바 코드 결함 몇 가지를 살펴보자.

결함 패턴 #1)
- Method ignores return value
 
아래 코드는 컴파일 에러가 나지 않지만 잘못된 곳이 있다. 어느 부분이 잘못되었을까?
String name = "bob";
name.replaceAll(“b”, “p”);
if(name.equals("pop"))
 
개발자는 두번째 라인을 통해 name String 변수내의 b가 p로 모두 치환될 것으로 생각한다.
그렇지만 String은 변하지 않는(immutable) 객체이다. replaceAll 메소드를 통해 변수의 값을 바꾸려고 해도 name 변수의 값은 변하지 않는다. 값이 바뀐 새로운 String 객체를 만들어낸다. replaceAll 메서드의 리턴값을 사용해서 위 코드는 아래와 같이 바꾸어야 한다.
 
String name = "bob";
String newname = "";
newname = name.replaceAll(“b”, “p”);
if(newname.equals("pop"))
 
String의 trim() 메서드도 위와 동일하다. trim() 메서드의 리턴값을 사용해야 원하는 결과를 얻을 수 있다.

결함 패턴 #2)
- Infinite recursive loop
하기 코드를 살펴 보자.
 
public String sendMessage(User user, String body, Date time) {
           return sendMessage(user, body, null);
}
개발자의 의도는 여러 메서드 오버로드에서 공통된 함수를 호출하는 것으로 보인다.
그렇지만 결과는 자기 자신을 무한 호출하게 된다.
자기 자신을 무한 호출하는 코드는 스택 오버플로우를 발생시키게 된다.
아래 코드를 살펴 보자.
public String foundType() {
           return this.foundType();
}
위 코드도 FindBugs를 돌려보면 Infinite recursive loop 결함이 탐지된다. 원래 개발자의 의도는 foundType이라는 프로퍼티 값을 리턴하는 것으로 보인다. 그렇지만 foundType()로 인해 결과적으로 자기 자신을 계속 호출하게 된다.

**6. 맺음말**
릴리즈가 중단된 FindBugs를 계승한 SpotBugs를 사용하자. 
https://spotbugs.github.io/index.html

**Comment by eGovFrameSupport** [comment]
[2021 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'21년 3월 31일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2021 전자정부 표준프레임워크 컨트리뷰션"을 개최 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL 또는 첨부의 QR코드 인식하셔서 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

![2021컨트리뷰션 경품발송 설문](https://user-images.githubusercontent.com/3771788/127802613-df9b5bbb-5db7-4fea-b653-abdb9e966cbf.png)

**Comment by ohorange21** [comment]
안녕하세요. 
표준프레임워크센터입니다.
먼저 참여해주셔서 감사합니다.
또한, SpotBougs에 대한 사용법 안내 감사드립니다.
