### ISSUE TITLE
설명과 문서가 필요해 보입니다.

### ISSUE THREAD

**Issue by moseyoon** [eGovFramework/egovframe-development#51]
해당 프로젝트에 대한 설명과 문서가 너무 없어서 아쉽네요.
저 같은 초보자가 어떻게 시작해야 하는지 알려주시면 좋을 것 같습니다. 

다른 프로젝트에는 README.md  파일이 작성되어 있어서, 프로젝트의 개요나 시작 방법에 대해서 자세히 나와 있습니다.
부디 이 프로젝트에서도 작성되어 있으면 좋겠습니다.

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 실시하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 소정의 기념품과 함께 표준프레임워크 오픈커뮤니티에서 커피쿠폰을 같이 발송 드릴 예정입니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by ohorange21** [comment]
안녕하세요. 
표준프레임워크센터입니다.
먼저, 참여해주셔서 감사드립니다.
README.md에 사용방법 및 빌드 방법이 적혀 있으니 참고해보시길 바랍니다.
감사합니다.
