### ISSUE TITLE
[Bug]: 모든 리소스들이 커밋 된게 맞나요?

### ISSUE THREAD

**Issue by bada-egov** [eGovFramework/egovframe-development#84]
### 연락처 Contact

bada.egov@gmail.com

### 오류 내용 Error Description

jdom, commons-lang, commons-io 등 외부 라이브러리 들이 프로젝트/lib 폴더에 아예 존재 하지도 않고
특히 egovframework.dev.imp.codegen.template 프로젝트에서 참조하는 eclipsework.jar,  abstractplugin.jar 는 구글링해도 검색이 안되네요.

하단 설명으로는 개발환경을 구성할 수가 없습니다.

**Comment by ohorange21** [comment]
안녕하세요.
표준프레임워크센터입니다.

말씀하신 해당 리소스가 빠진 것을 확인하였고
새로 올려두었습니다.

표준프레임워크에 관심을 가지고 제보해 주셔서
대단히 감사 드립니다.

**Comment by bada-k** [comment]
git lfs pull
git lfs fetch --all
위 두 명령어로 lfs 파일 다운로드를 시도해 봤는데 아래와 같은 메시지가 표시되고 다운로드가 안되네요.
```
git lfs fetch --all
fetch: 102 objects found, done.                                                                                                                          
fetch: Fetching all references...
[b786d72eb6e2778ef83afb96212de54f2e5ee7ae1268bc7f637d44950c6e6038] Object does not exist on the server: [404] Object does not exist on the server        
[e21b4ae2d47e94299f18f87d156753cb2d67e93ba2c5a63bab2b46415e5d5cb7] Object does not exist on the server: [404] Object does not exist on the server
.....
``` 

SourceTree GUI 툴로 Clone을 시도해도 다음 같은 내용이 표시됩니다.
<img width="590" alt="SourceTree_lfs" src="https://github.com/eGovFramework/egovframe-development/assets/35361987/3efdba22-94f7-42be-900d-980fea33d081">

**Comment by ohorange21** [comment]
안녕하세요.
표준프레임워크센터입니다.

말씀하신 사항은 확인 중에 있으며
추후에 댓글로 답변드리도록 하겠습니다.

감사합니다.

**Comment by ohorange21** [comment]
안녕하세요.
표준프레임워크센터입니다.

Git LFS를 사용하지 않고 라이브러리들을 올려두었으니
확인해보시길 바랍니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시하고 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.
