### ISSUE TITLE
[문의]: Git LFS 파일 다운로드 방법

### ISSUE THREAD

**Issue by bada-egov** [eGovFramework/egovframe-development#89]
### 연락처 Contact

bada.egov@gmail.com

### 추가 요청 기능명 Feature Name

Git LFS 파일 다운로드 방법

### 기능 상세 설명 Feature Description

안녕하세요.

git lfs pull
git lfs fetch --all
위 두 명령어로 lfs 파일 다운로드를 시도해 봤는데 아래와 같은 메시지가 표시되고 다운로드가 안되네요.
```
git lfs fetch --all
fetch: 102 objects found, done.                                                                                                                          
fetch: Fetching all references...
[b786d72eb6e2778ef83afb96212de54f2e5ee7ae1268bc7f637d44950c6e6038] Object does not exist on the server: [404] Object does not exist on the server        
[e21b4ae2d47e94299f18f87d156753cb2d67e93ba2c5a63bab2b46415e5d5cb7] Object does not exist on the server: [404] Object does not exist on the server
.....
``` 

SourceTree GUI 툴로 Clone을 시도해도 다음 같은 내용이 표시됩니다.
<img width="590" alt="SourceTree_lfs" src="https://github.com/eGovFramework/egovframe-development/assets/35361987/3efdba22-94f7-42be-900d-980fea33d081">

**※ 기존 이슈에 Comment로 달면 알림이 안 가는 것 같네요.
이런 문의를 이슈에 계속 등록하면 되는지 아니면 질문/답변을 위한 게시판이 별도로 있는지 알려주세요.**

**Comment by ohorange21** [comment]
안녕하세요.
표준프레임워크센터입니다.

말씀하신 사항은 확인 중에 있으며
추후에 댓글로 답변드리도록 하겠습니다.

감사합니다.

**Comment by ohorange21** [comment]
안녕하세요.
표준프레임워크센터입니다.

Git LFS를 사용하지 않고 라이브러리들을 올려두었으니
확인해보시길 바랍니다.

감사합니다.
